image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - source /opt/ros/setup.sh

format:
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../
    - make camera_node_format
    - test -z "$(git diff)" && exit 0 || exit 1
  allow_failure: false

example-build:
  script:
    - colcon build
  allow_failure: false
