image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - source /opt/ros/setup.sh

format:
  script:
    - colcon test
    - colcon test-result
  allow_failure: false

example-build:
  script:
    - colcon build
  allow_failure: false
