image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - source /opt/ros/setup.sh

example-build:
  script:
    - colcon build
    - colcon test
    - colcon test-result --verbose
  allow_failure: false
